"use client";

import { Bell, CalendarDays, ChevronDown, ChevronRight, ClipboardList, Droplets, Gift, Home, MapPin, Menu, Search, ShieldCheck, Star, X } from "lucide-react";
import { useState, type ReactNode } from "react";
import { HemovaLogo } from "./hemova-logo";
import { DonorAccountFooter } from "./donor-account-footer";
import { ScrollReveal, StaggerReveal } from "./scroll-reveal";

const nav = [[Home, "Overview", "/donor"], [Droplets, "Donate", "/donor/donate"], [ClipboardList, "Request", "/donor/request"], [Gift, "Rewards", "/donor/rewards"]] as const;
const donations = [["10 Dec 2024", "Korle Bu Teaching Hospital", "O+", "Completed", "200"], ["15 Sep 2024", "University of Ghana Drive", "O+", "Completed", "200"], ["12 Jun 2024", "Ridge Hospital", "O+", "Completed", "150"], ["20 Mar 2024", "Accra Mall Blood Drive", "O+", "Completed", "150"], ["05 Jan 2024", "37 Military Hospital", "O+", "Completed", "150"]];
const requests = [["REQ-2024-0021", "Korle Bu Teaching Hospital", "O−", "2", "Active", "10 May 2025"], ["REQ-2024-0014", "Ridge Hospital", "B+", "1", "Fulfilled", "21 Apr 2025"]];

function Navigation({ mobile = false, close }: { mobile?: boolean; close?: () => void }) {
  return <nav className={mobile ? "app-mobile-nav" : "app-sidebar"} aria-label="Dashboard navigation">{!mobile && <HemovaLogo />}<div className="app-nav-items">{nav.map(([Icon, label, href], index) => <a href={href} onClick={close} className={index === 0 ? "active" : ""} key={label}><Icon size={19} /><span>{label}</span></a>)}</div>{!mobile && <div className="overview-sidebar-account"><DonorAccountFooter /></div>}</nav>;
}

export function DonorDashboard() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <div className="app-shell donor-dashboard exact-dashboard"><Navigation /><header className="app-header"><button className="app-menu" onClick={() => setMenuOpen(true)} aria-label="Open navigation"><Menu /></button><div className="mobile-app-logo"><HemovaLogo /></div><div className="overview-header-context"><strong>Overview</strong><span>Welcome back, Yusif 👋</span></div><div className="app-search"><Search size={17} /><input aria-label="Search Hemova" placeholder="Search for hospitals, campaigns, requests..." /></div><div className="app-header-actions"><div className="overview-bell"><Bell size={19} /><b>3</b></div><a className="overview-profile" href="/donor/profile"><span className="profile-photo">YA</span><span><strong>Yusif Abubakar</strong><small>Donor</small></span><ChevronDown size={15} /></a></div></header>{menuOpen && <div className="app-drawer"><div className="drawer-head"><HemovaLogo /><button onClick={() => setMenuOpen(false)} aria-label="Close navigation"><X /></button></div><Navigation mobile close={() => setMenuOpen(false)} /></div>}
    <main className="dashboard-main exact-dashboard-main"><div className="exact-dashboard-title"><h1>Your impact</h1><a className="button button-secondary" href="/donor/profile">View full profile <ChevronRight size={15} /></a></div>
      <StaggerReveal className="exact-metrics"><Metric icon={<Droplets />} value="7" label="Donations" note="Confirmed donations" tone="red" /><Metric icon={<ClipboardList />} value="2" label="Requests" note="Blood requests made" tone="purple" /><Metric icon={<Star />} value="1,450" label="Hemova Points" note="Points earned" tone="gold" /><Metric icon={<ShieldCheck />} value="3" label="Certificates" note="Earned certificates" tone="green" /></StaggerReveal>
      <ScrollReveal as="section" className="eligibility-banner"><span><Droplets size={20} /></span><div><strong>Your next possible donation</strong><p>You may be eligible to donate again from <b>Tue, 10 Jun 2025</b></p><small>Final eligibility is determined at the donation centre.</small></div><a className="button" href="/donor/centres">Find a centre</a></ScrollReveal>
      <ScrollReveal className="exact-content-grid"><div className="exact-main-column"><DataTable title="Recent donations" link="View all" headers={["Date", "Facility / Campaign", "Blood Type", "Status", "Points", "Certificate"]}>{donations.map((row) => <div className="exact-table-row" key={row[0]}>{row.map((cell, index) => <span key={index} className={index === 2 ? "blood-pill" : index === 3 ? "status-pill completed" : index === 5 ? "certificate-icon" : index === 4 ? "points-cell" : ""}>{index === 5 ? <ShieldCheck size={15} /> : cell}</span>)}</div>)}</DataTable><DataTable title="My blood requests" link="View all" headers={["Request ID", "Hospital", "Blood Type", "Units", "Status", "Date"]}>{requests.map((row) => <div className="exact-table-row" key={row[0]}>{row.map((cell, index) => <span key={index} className={index === 2 ? "blood-pill" : index === 4 ? `status-pill ${cell.toLowerCase()}` : ""}>{cell}</span>)}</div>)}</DataTable><section className="activity-card"><div className="section-heading-row"><h2>Recent activity</h2><a href="/donor/notifications">View all</a></div><StaggerReveal className="activity-grid"><Activity icon={<Droplets />} title="Donation confirmed" copy="Korle Bu Teaching Hospital" date="10 Dec 2024" /><Activity icon={<ClipboardList />} title="Blood request submitted" copy="Korle Bu Teaching Hospital" date="10 May 2025" /><Activity icon={<Star />} title="Points earned" copy="For donation on 10 Dec 2024" date="10 Dec 2024" /><Activity icon={<ShieldCheck />} title="Certificate generated" copy="Donation on 10 Dec 2024" date="12 Dec 2024" /></StaggerReveal></section></div><DashboardAside /></ScrollReveal>
    </main><div className="bottom-tabs">{nav.map(([Icon, label, href], i) => <a className={i === 0 ? "active" : ""} href={href} key={label}><Icon size={18} /><span>{label}</span></a>)}</div></div>;
}

function DashboardAside() {
  const centres = [["Korle Bu Teaching Hospital", "4.2 km away", "Open now"], ["Ridge Hospital", "6.1 km away", "Open now"], ["37 Military Hospital", "7.3 km away", "Closes 5:00 PM"]];
  const drives = [["24", "MAY", "Accra Mall Blood Drive", "Accra Mall, Spintex Road", "9:00 AM – 4:00 PM", "120 slots left"], ["07", "JUN", "University of Ghana Drive", "University of Ghana, Legon", "9:00 AM – 3:00 PM", "80 slots left"]];
  return <aside className="exact-side-column"><section className="quick-actions-card"><div className="section-heading-row"><h2>Quick actions</h2></div><div className="quick-action-grid"><a href="/donor/donate"><Droplets /><span>Donate<br />blood</span></a><a href="/donor/request"><ClipboardList /><span>Request<br />blood</span></a><a href="/donor/centres"><MapPin /><span>Find a<br />centre</span></a><a href="/donor/campaigns"><CalendarDays /><span>View<br />campaigns</span></a></div></section><section className="nearby-card"><div className="section-heading-row"><h2>Nearby donation centres</h2><a href="/donor/centres">View all</a></div>{centres.map(([name, distance, status], i) => <article key={name}><span className={`nearby-thumb nearby-${i}`} /><div><strong>{name}</strong><small><ShieldCheck size={10} /> Verified</small><p>{distance} <i>·</i> Accra</p></div><b className={i === 2 ? "closing" : "open"}>{status}</b></article>)}</section><section className="drives-card"><div className="section-heading-row"><h2>Upcoming blood drives</h2><a href="/donor/campaigns">View all</a></div>{drives.map((drive) => <article key={drive[2]}><div className="drive-date"><b>{drive[0]}</b><span>{drive[1]}</span></div><div><strong>{drive[2]}</strong><small><ShieldCheck size={10} /> Verified</small><p>{drive[3]}</p><p>{drive[4]} <i>·</i> {drive[5]}</p></div><button className="button">Join</button></article>)}</section></aside>;
}

function Metric({ icon, value, label, note, tone }: { icon: ReactNode; value: string; label: string; note: string; tone: string }) { return <article className={`exact-metric ${tone}`}><span className="metric-bubble">{icon}</span><div><strong>{value}</strong><b>{label}</b><small>{note}</small></div></article>; }
function DataTable({ title, link, headers, children }: { title: string; link: string; headers: string[]; children: ReactNode }) { return <section className="exact-data-card"><div className="section-heading-row"><h2>{title}</h2><a href="#top">{link}</a></div><div className="exact-table"><div className="exact-table-head">{headers.map((header) => <span key={header}>{header}</span>)}</div>{children}</div></section>; }
function Activity({ icon, title, copy, date }: { icon: ReactNode; title: string; copy: string; date: string }) { return <article><span>{icon}</span><div><strong>{title}</strong><p>{copy}</p><small>{date}</small></div>{title === "Donation confirmed" || title === "Points earned" ? <b>+200 pts</b> : null}</article>; }
