"use client";

import { Activity, BadgeCheck, Bell, Building2, CalendarDays, ChevronRight, ClipboardCheck, FileCheck2, Gift, HeartHandshake, LayoutDashboard, Menu, Search, Settings, ShieldCheck, Stethoscope, Users, X } from "lucide-react";
import { useState } from "react";
import { HemovaLogo } from "./hemova-logo";
import { ScrollReveal } from "./scroll-reveal";

type Role = "hospital" | "blood-bank" | "organization" | "requester" | "partner";
type Config = { title:string; entity:string; subtitle:string; metrics:[string,string,string][]; nav:string[]; action:string; table:string[]; rows:string[][]; fhir:string[] };
const configs: Record<Role, Config> = {
 "hospital": { title:"Hospital workspace",entity:"Korle Bu Teaching Hospital",subtitle:"Coordinate verified blood requests and donor responses safely.",metrics:[["Active requests","04","1 critical"],["Donors responding","26","Across active requests"],["Appointments today","12","3 arrivals confirmed"],["Fulfilled this month","18","+12% from August"]],nav:["Overview","Blood requests","Donor matching","Donor responses","Donations","Appointments","Blood drives","Programs","Analytics","Team","Notifications","FHIR integration","Audit log","Settings"],action:"Create blood request",table:["Request ID","Blood group","Units","Responses","Status","Deadline"],rows:[["REQ-00842","O−","2","6","Critical","Today, 6:00 PM"],["REQ-00831","A+","4","12","Active","Tomorrow"],["REQ-00819","O+","3","8","Partially fulfilled","16 Sep"]],fhir:["Organization · Korle Bu Teaching Hospital","Location · Donation coordination site","Appointment · donor arrival scheduling","ServiceRequest · authorized request exchange","Consent & AuditEvent · minimum necessary access"] },
 "blood-bank": { title:"Blood bank workspace",entity:"National Blood Service",subtitle:"Manage donation operations and authorized inventory integrations.",metrics:[["Appointments today","28","8 expected in next hour"],["Completed donations","86","This month"],["Inventory integration","Connected","Last sync 10:20 AM"],["Upcoming campaigns","03","In next 30 days"]],nav:["Overview","Blood requests","Donor matching","Donors","Donations","Pre-donation","Appointments","Inventory","Donation centres","Blood drives","Rewards","Certificates","Reports","Team","FHIR integration","Audit log","Settings"],action:"Add appointment",table:["Appointment","Donor","Time","Campaign","Status","Arrival"],rows:[["APT-4021","Yusif A.","10:00 AM","—","Booked","Expected"],["APT-4022","Esi A.","10:30 AM","Accra Drive","Checked in","Arrived"],["APT-4023","Kwame D.","11:00 AM","—","Booked","Expected"]],fhir:["Organization & Location · blood bank identity","Appointment / Schedule / Slot · capacity management","Procedure · confirmed donation only","BiologicallyDerivedProduct · integration-ready inventory reference","Observation & DiagnosticReport · screening results under authorization"] },
 "organization": { title:"Campaign organizer",entity:"Accra Rotary Club",subtitle:"Create safe community blood drives and coordinate participation.",metrics:[["Active campaigns","02","1 starts this week"],["Registrations","94","Across campaigns"],["Confirmed attendance","68","Reported by centres"],["Volunteers","12","3 pending confirmation"]],nav:["Overview","My blood drives","Create blood drive","Registrations","Donors","Donations","Blood types","Volunteers","Communications","Certificates","Reports","Organization","Team","Verification","Settings"],action:"Create blood drive",table:["Campaign","Date","Location","Registered","Attendance","Status"],rows:[["Accra Community Blood Drive","28 Sep","Osu","42","—","Published"],["Community Donation Day","12 Oct","Korle Bu","35","—","Published"],["Airport City Drive","26 Oct","Airport","17","—","Draft"]],fhir:["Organization · verified organizer record","Location · event site mapping","Appointment · optional booked donation slot","Communication · consented campaign updates","Consent · communication preference respected"] },
 "requester": { title:"Request coordination",entity:"Verified care requester",subtitle:"Coordinate a verified facility request without exposing patient details.",metrics:[["Open requests","01","Facility verified"],["Donor responses","06","Private responses"],["Arrival plans","03","For today"],["Request status","Active","Deadline 6:00 PM"]],nav:["Overview","My requests","Responses","Arrival plans","Messages","Safety guidance","Notifications","Settings"],action:"View request",table:["Request","Blood group","Facility","Responses","Status","Deadline"],rows:[["REQ-00842","O−","Korle Bu Teaching Hospital","6","Active","Today, 6:00 PM"]],fhir:["No Patient resource is exposed in this workspace","ServiceRequest · facility-managed coordination reference","Communication · permitted operational updates","Consent · purpose-limited disclosure","AuditEvent · every access is traceable"] },
 "partner": { title:"Recognition partner",entity:"MedPharm Osu",subtitle:"Manage approved donor recognition offers without medical data access.",metrics:[["Active offers","02","Available today"],["Issued rewards","48","This month"],["Redemptions","37","77% redeemed"],["Locations","01","Osu, Accra"]],nav:["Overview","Offers","Redemptions","Validate code","Locations","Analytics","Team","Verification","Settings"],action:"Create offer",table:["Reward","Issued","Redeemed","Availability","Status","Updated"],rows:[["Wellness check","11","8","32 remaining","Active","Today"],["Pharmacy support","37","29","70 remaining","Active","Yesterday"]],fhir:["No Patient, Observation, or donation history access","Organization · approved partner identity","Task · optional redemption workflow reference","AuditEvent · redemption validation trace","Consent boundary enforced by role"] },
};

export function InstitutionDashboard({ role, initialTab }: { role:Role; initialTab?: string }) { const config=configs[role]; const decoded=initialTab?.split("-").map(word=>word[0]?.toUpperCase()+word.slice(1)).join(" "); const [tab,setTab]=useState(config.nav.includes(decoded ?? "") ? decoded! : "Overview"); const [drawer,setDrawer]=useState(false); const [notice,setNotice]=useState(""); const choose=(value:string)=>{setTab(value);window.history.pushState({},"",`/${role}/${value.toLowerCase().replaceAll(" ","-")}`)}; return <main className="institution-shell"><aside className="institution-sidebar"><HemovaLogo/><p>{config.entity}</p><RoleNav config={config} tab={tab} setTab={choose}/></aside><header className="institution-header"><button onClick={()=>setDrawer(true)}><Menu/></button><div><strong>{tab}</strong><span>{config.title}</span></div><div className="institution-search"><Search size={16}/><input placeholder="Search workspace" aria-label="Search workspace"/></div><button className="button" onClick={()=>setNotice(`${config.action} workflow opened.`)}>{config.action}</button><button className="institution-bell"><Bell size={18}/><i/></button></header>{drawer&&<div className="institution-drawer"><div><HemovaLogo/><button onClick={()=>setDrawer(false)}><X/></button></div><RoleNav config={config} tab={tab} setTab={(value)=>{choose(value);setDrawer(false)}}/></div>}<section className="institution-main"><ScrollReveal>{notice&&<div className="feature-success"><ShieldCheck size={18}/><span>{notice}</span><button onClick={()=>setNotice("")}>×</button></div>}{tab==="Overview"?<Overview config={config} setTab={choose}/>:tab==="FHIR integration"?<Fhir config={config}/>:<Tab config={config} tab={tab} setNotice={setNotice}/>}</ScrollReveal></section></main> }
function RoleNav({ config,tab,setTab }: {config:Config;tab:string;setTab:(value:string)=>void}) { return <nav>{config.nav.map(label=><button key={label} onClick={()=>setTab(label)} className={label===tab?"active":""}>{label==="Overview"?<LayoutDashboard size={17}/>:label.includes("FHIR")?<FileCheck2 size={17}/>:label.includes("Audit")?<ClipboardCheck size={17}/>:label.includes("Campaign")?<CalendarDays size={17}/>:label.includes("Team")?<Users size={17}/>:label.includes("Settings")?<Settings size={17}/>:label.includes("Offer")||label.includes("Redemption")?<Gift size={17}/>:label.includes("Appointment")?<CalendarDays size={17}/>:<Activity size={17}/>}<span>{label}</span></button>)}</nav> }
function Overview({config,setTab}:{config:Config;setTab:(v:string)=>void}) { return <><div className="institution-title"><p className="dashboard-kicker">Operations workspace</p><h1>{config.entity}</h1><p>{config.subtitle}</p></div><div className="institution-kpis">{config.metrics.map(([label,value,detail],index)=><article key={label}><span>{index===0?<HeartHandshake size={19}/>:index===1?<Users size={19}/>:index===2?<Building2 size={19}/>:<BadgeCheck size={19}/>}</span><p>{label}</p><strong>{value}</strong><small>{detail}</small></article>)}</div><section className="institution-grid"><article className="admin-panel institution-chart"><header><div><h2>Activity overview</h2><p>Operational activity over the last 6 months</p></div><button>Last 6 months</button></header><div className="chart-area"><svg viewBox="0 0 700 190"><path className="chart-fill" d="M8,158 L90,146 L170,153 L252,110 L332,124 L414,82 L496,95 L578,58 L692,31 L692,183 L8,183Z"/><path className="chart-line" d="M8,158 L90,146 L170,153 L252,110 L332,124 L414,82 L496,95 L578,58 L692,31"/></svg><div className="chart-labels"><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep</span></div></div></article><article className="admin-panel institution-actions"><h2>Next actions</h2><p>Keep the most important work moving.</p><button onClick={()=>setTab(config.nav[1])}>Review {config.nav[1]} <ChevronRight size={15}/></button><button onClick={()=>setTab(config.nav.at(-2) ?? "Settings")}>Open verification & settings <ChevronRight size={15}/></button><button onClick={()=>setTab(config.nav.includes("FHIR integration")?"FHIR integration":"Reports")}>View integration status <ChevronRight size={15}/></button></article></section><DataPanel config={config} title={config.nav[1]}/></> }
function Fhir({config}:{config:Config}) { return <><div className="institution-title"><p className="dashboard-kicker">FHIR R4 ready</p><h1>Interoperability</h1><p>Configure standards-based exchanges without exposing more data than an authorized workflow needs.</p></div><section className="fhir-card"><header><div><FileCheck2 size={22}/><div><h2>FHIR R4 exchange readiness</h2><p>Designed for HL7 FHIR interoperability. Not a claim of formal conformance.</p></div></div><span>Configured</span></header><ul>{config.fhir.map(item=><li key={item}><CheckMark/>{item}</li>)}</ul><footer><button className="button">Configure connection</button><button className="button button-secondary">View mapping guide</button></footer></section></> }
function Tab({config,tab,setNotice}:{config:Config;tab:string;setNotice:(v:string)=>void}) { return <><div className="institution-title"><p className="dashboard-kicker">{config.title}</p><h1>{tab}</h1><p>Manage {tab.toLowerCase()} with a clear, role-appropriate operational view.</p></div><DataPanel config={config} title={tab} setNotice={setNotice}/></> }
function DataPanel({config,title,setNotice}:{config:Config;title:string;setNotice?:(v:string)=>void}) { return <section className="admin-panel institution-table"><header><div><h2>{title}</h2><p>Live operational records</p></div><div className="admin-table-tools"><div><Search size={15}/><input placeholder="Search records"/></div><button className="table-filter">Filter</button></div></header><div className="table-scroll"><table><thead><tr>{config.table.map(head=><th key={head}>{head}</th>)}</tr></thead><tbody>{config.rows.map((row,i)=><tr key={`${title}${i}`}>{row.map((cell,j)=><td key={`${cell}${j}`}>{["Active","Published","Booked","Confirmed","Connected","Critical","Checked in"].includes(cell)?<span className={cell==="Critical"?"table-urgency":"table-status"}>{cell}</span>:cell}</td>)}</tr>)}</tbody></table></div>{setNotice&&<footer><button className="button button-secondary" onClick={()=>setNotice(`Selected ${title.toLowerCase()} record opened.`)}>Open selected record <ChevronRight size={15}/></button></footer>}</section> }
function CheckMark(){return <span className="fhir-check">✓</span>}
